# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
theme: jekyll-theme-tactile
title: Welcome to NYU E-Cig Study Page
description: adfklaksl

# NOTE: Replacing this next line with your own URL
production_url : https://sashaeiou.github.io/study_page

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown


